# Generated by Django 5.2.8
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models

# [중요 1] 이 줄이 꼭 있어야 합니다!
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        # [중요 2] 테이블 만들기 전에 "벡터 기능 켜!" 라고 명령해야 합니다.
        VectorExtension(),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PoliceFoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atc_id", models.CharField(max_length=50)),
                ("fd_sn", models.CharField(max_length=10)),
                ("item_name", models.CharField(max_length=200, null=True)),
                ("category", models.CharField(max_length=100, null=True)),
                ("found_location", models.CharField(max_length=200, null=True)),
                ("found_date", models.DateField(null=True)),
                ("item_desc", models.TextField(null=True)),
                ("ai_generated_desc", models.TextField(null=True)),
                ("police_image_url", models.CharField(max_length=500, null=True)),
                ("vlm_embedding", pgvector.django.vector.VectorField(null=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "police_found_item",
                "unique_together": {("atc_id", "fd_sn")},
            },
        ),
        migrations.CreateModel(
            name="UserLostItem",
            fields=[
                ("request_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "original_image_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("vlm_embedding", pgvector.django.vector.VectorField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.users",
                    ),
                ),
            ],
            options={"db_table": "user_lost_item"},
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("noti_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("atc_id", models.CharField(max_length=50)),
                ("fd_sn", models.CharField(max_length=10)),
                ("similarity_score", models.FloatField(null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userlostitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.users",
                    ),
                ),
            ],
            options={"db_table": "notification_log"},
        ),
    ]
