# Generated by Django 5.2.8 on 2025-12-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="policefounditem",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
